name: Python Package using Conda

on: [pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Test with unittest
      run: |
        cd Mytorch
        python -m unittest discover -s Test -p "Test*.py"  
